import type { MediaMetadata } from "../media/model";
import { realRefreshClient } from "./http";
import { strictConfiguration } from "./configuration";
export type Platform="instagram"|"tiktok"|"youtube"; export type CoverSource="uploaded_image"|"extracted_frame"|"rendered_cover";
export type InstagramConfiguration={platform:"instagram";enabled:boolean;override?:string;cover?:CoverSource;shareToFeed?:boolean}; export type TikTokConfiguration={platform:"tiktok";enabled:boolean;override?:string;privacy?:string;allowComments?:boolean;allowDuet?:boolean;allowStitch?:boolean;cover?:"extracted_frame";isAigc?:boolean}; export type YouTubeConfiguration={platform:"youtube";enabled:boolean;title:string;override?:string;privacy?:"public"|"private"|"unlisted";descriptionOverride?:string;madeForKids?:boolean;containsSyntheticMedia?:boolean;thumbnail?:CoverSource}; export type PlatformConfiguration=InstagramConfiguration|TikTokConfiguration|YouTubeConfiguration; export type PlatformConfig=PlatformConfiguration;
export type Account={connected:boolean;eligible:boolean;scopes:string[];displayName?:string;remoteAccountId?:string;dynamic?:{privacyOptions?:string[];commentDisabled?:boolean;duetDisabled?:boolean;stitchDisabled?:boolean;maxVideoPostDurationSec?:number}}; export type Capability={available:boolean;options?:string[];reason?:string}; export type Preflight={platform:Platform;status:"Ready"|"NotReady";reasons:string[];refreshedAt:string;account?:Pick<Account,"connected"|"eligible"|"displayName"|"remoteAccountId">;capabilities?:Record<string,Capability>};
const out=(p:Platform,r:string[],a:Account,c:Record<string,Capability>):Preflight=>({platform:p,status:r.length?"NotReady":"Ready",reasons:r,refreshedAt:new Date().toISOString(),account:{connected:a.connected,eligible:a.eligible,displayName:a.displayName,remoteAccountId:a.remoteAccountId},capabilities:c}); const base=(s:string[],i:{media:MediaMetadata|null;account:Account})=>{const r:string[]=[];if(!i.account.connected)r.push("Cuenta no conectada");if(!i.account.eligible)r.push("Cuenta no elegible");for(const x of s)if(!i.account.scopes.includes(x))r.push(`Scope requerido: ${x}`);if(!i.media)r.push("Video requerido");else if(!Number.isFinite(i.media.width)||!Number.isFinite(i.media.height)||i.media.width<=0||i.media.height<=0||!Number.isFinite(i.media.duration)||!i.media.duration||i.media.duration<=0)r.push("Metadata de video inválida");return r;}; const unavailable=():Account=>({connected:false,eligible:false,scopes:[]});
export type CoverAsset={id:string;draftId:string;status:string;kind:string;sourceVideoId?:string}; export interface PlatformAdapter<C extends PlatformConfiguration=PlatformConfiguration>{readonly platform:Platform;requiredScopes:string[];refreshAccount(account?:Account,token?:string):Promise<Account>;capabilities(account:Account):Record<string,Capability>;validate(input:{caption:string;config:C;media:MediaMetadata|null;account:Account;capabilities:Record<string,Capability>;coverAsset?:CoverAsset;draftId?:string;videoId?:string}):Preflight;}
export class InstagramAdapter implements PlatformAdapter<InstagramConfiguration>{readonly platform="instagram" as const;requiredScopes=["instagram_basic","instagram_content_publish"];async refreshAccount(a?:Account,t?:string){return t?realRefreshClient.refresh(this.platform,t,a?.remoteAccountId??""):unavailable();}capabilities(a:Account){const can=a.connected&&a.eligible&&this.requiredScopes.every(s=>a.scopes.includes(s));return {caption:{available:true},cover:{available:can,options:can?["extracted_frame"]:[]},shareToFeed:{available:can}};}validate(i:{caption:string;config:InstagramConfiguration;media:MediaMetadata|null;account:Account;capabilities:Record<string,Capability>}){const r=base(this.requiredScopes,i);if(i.config.cover&&(!i.capabilities.cover?.available||i.config.cover!=="extracted_frame"||!i.media))r.push("Cover asset/capability unavailable");if(i.caption.length>2200)r.push("Caption supera 2200 caracteres");if(i.media&&(!["mp4","mov"].some(c=>i.media?.container?.split(",").includes(c))||!["h264","hevc"].includes(i.media.videoCodec??"")))r.push("Container o codec incompatible");if(i.media&&((i.media.duration??0)<3||(i.media.duration??0)>900))r.push("Duración fuera de 3-900 segundos");return out(this.platform,r,i.account,this.capabilities(i.account));}}
export class TikTokAdapter implements PlatformAdapter<TikTokConfiguration>{readonly platform="tiktok" as const;requiredScopes=["video.publish"];async refreshAccount(a?:Account,t?:string){return t?realRefreshClient.refresh(this.platform,t,a?.remoteAccountId??""):unavailable();}capabilities(a:Account){return {privacy:{available:!!a.dynamic?.privacyOptions,options:a.dynamic?.privacyOptions},comments:{available:a.dynamic?.commentDisabled===false},duet:{available:a.dynamic?.duetDisabled===false},stitch:{available:a.dynamic?.stitchDisabled===false},cover:{available:true,options:["extracted_frame"]}};}validate(i:{caption:string;config:TikTokConfiguration;media:MediaMetadata|null;account:Account;capabilities:Record<string,Capability>;coverAsset?:CoverAsset;draftId?:string;videoId?:string}){const r=base(this.requiredScopes,i),d=i.account.dynamic;if(i.config.cover){const a=i.coverAsset;if(!a)r.push("cover_asset_missing");else{if(a.draftId!==i.draftId)r.push("cover_asset_wrong_draft");if(a.status!=="ready")r.push("cover_asset_not_ready");if(a.kind!=="extracted_frame")r.push("cover_asset_type_invalid");if(a.sourceVideoId!==i.videoId)r.push("cover_asset_wrong_video");}}if(i.caption.length>2200)r.push("Caption supera 2200 caracteres");if(i.config.allowComments&&d?.commentDisabled!==false)r.push("Comentarios no disponibles");if(i.config.allowDuet&&d?.duetDisabled!==false)r.push("Duet no disponible");if(i.config.allowStitch&&d?.stitchDisabled!==false)r.push("Stitch no disponible");if(!d?.privacyOptions?.length)r.push("Creator Info no disponible");if(!i.config.privacy)r.push("Privacy obligatorio");else if(!d?.privacyOptions?.includes(i.config.privacy))r.push("Privacy no permitido por la cuenta");if(!d?.maxVideoPostDurationSec)r.push("Límite dinámico de duración no disponible");else if(i.media?.duration!==undefined&&i.media.duration>d.maxVideoPostDurationSec)r.push("Duración supera el límite actual");return out(this.platform,r,i.account,this.capabilities(i.account));}}
export class YouTubeAdapter implements PlatformAdapter<YouTubeConfiguration>{readonly platform="youtube" as const;requiredScopes=["https://www.googleapis.com/auth/youtube.upload"];async refreshAccount(a?:Account,t?:string){return t?realRefreshClient.refresh(this.platform,t,a?.remoteAccountId??""):unavailable();}capabilities(){return {title:{available:true},description:{available:true},privacy:{available:true,options:["public","private","unlisted"]},thumbnail:{available:false,options:[]},madeForKids:{available:true},containsSyntheticMedia:{available:true}};}validate(i:{caption:string;config:YouTubeConfiguration;media:MediaMetadata|null;account:Account;capabilities:Record<string,Capability>;coverAsset?:CoverAsset;draftId?:string;videoId?:string}){const r=base(this.requiredScopes,i),t=i.config.title;if(!t.trim())r.push("Título obligatorio");if(/[<>]/.test(t)||/[<>]/.test(i.caption))r.push("Texto contiene caracteres no permitidos");if(new TextEncoder().encode(i.caption).length>5000)r.push("Descripción supera 5000 bytes");if(i.config.madeForKids===undefined)r.push("Indica si es contenido para niños");if(i.config.containsSyntheticMedia===undefined)r.push("Indica si contiene media sintética");if([...t].length>100)r.push("Título supera 100 caracteres");if(!i.config.privacy)r.push("Privacy obligatorio");if(i.media&&(!i.media.width||!i.media.height||i.media.duration===undefined||i.media.duration>180||i.media.width>i.media.height||i.media.duration<=0))r.push("Video no elegible como Short");return out(this.platform,r,i.account,this.capabilities());}}
export const adapterRegistry={instagram:new InstagramAdapter(),tiktok:new TikTokAdapter(),youtube:new YouTubeAdapter()} as const;
export const parseConfiguration = strictConfiguration;
export function resolveEffectivePlatformConfiguration(caption:string,c:PlatformConfiguration){return c.platform==="youtube"?{...c,descriptionOverride:c.descriptionOverride??caption}:{...c,effectiveCaption:c.override??caption};}
export function validatePlatform(p:Platform,input:{caption:string;config:Record<string,unknown>;media:MediaMetadata|null;account:Account;capabilities:Record<string,Capability>}):Preflight{
 const config=strictConfiguration({...input.config,platform:p});
 switch(config.platform){
 case "instagram":return adapterRegistry.instagram.validate({...input,config});
 case "tiktok":return adapterRegistry.tiktok.validate({...input,config});
 case "youtube":return adapterRegistry.youtube.validate({...input,config});
 }
}
export function globalPreflight(r:Preflight[]){return {status:r.length>0&&r.every(x=>x.status==="Ready")?"Ready":"NotReady" as const,reasons:r.flatMap(x=>x.reasons.map(y=>`${x.platform}: ${y}`))};}